# Site settings
title: Stylish Portfolio
email: theme@viennalabs.com
description: > # this means to ignore newlines until "baseurl:"
  A Jekyll implementation of the Stylish Portfolio template by Start Bootstrap.
  Stylish Portfolio is a one page Bootstrap portfolio theme with off canvas
  navigation and smooth scrolling through content sections.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "127.0.0.1:4001" # the base hostname & protocol for your site

twitter_username: volnyio
github_username:  volny

# Build settings
markdown: kramdown
